server:
  port: 8083

spring:
  application:
    name: incident-service
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db
    username: black
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: incident-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    alerts: black.alerts
    incidents: black.incidents